In [22]:
#IMPORTING THE LIBRARIES

In [1]:
import pandas as pd

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB

In [8]:
from sklearn import svm

In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:
import numpy as np

In [11]:
import nltk

In [12]:
from nltk.corpus import stopwords

In [13]:
import string

In [2]:
df = pd.read_csv('messages.csv')

In [3]:
df.head()

subject  \
0            job posting - apple-iss research center   
1                                                NaN   
2  query : letter frequencies for text identifica...   
3                                               risk   
4                           request book information   

                                             message  label  
0  content - length : 3386 apple-iss research cen...      0  
1  lang classification grimes , joseph e . and ba...      0  
2  i am posting this inquiry for sergei atamas ( ...      0  
3  a colleague and i are researching the differin...      0  
4  earlier this morning i was on the phone with a...      0

In [4]:
df.shape

(2893, 3)

In [14]:
#Get the columns name
df.columns

Index(['subject', 'message', 'label'], dtype='object')

In [16]:
#Check the Duplicate and remove them
df.drop_duplicates(inplace=True)

In [17]:
#again check the shape of dataset
df.shape

(2876, 3)

In [18]:
df.isnull().sum()

subject    62
message     0
label       0
dtype: int64

In [21]:
#Downoad the stopword packages
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Ravindra
[nltk_data]     singh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [30]:
def process_text(text):
    
    #1 remove punctuation
    #2 remoove stopwords
    #3 remove a list of clean text words
    
    #1 
    nopunctuation = [char for char in text if char not in string.punctuation ]
    nopunctuation = ''.join(nopunctuation)
    
    #2 
    clean_words = [word for word in nopunctuation.split() if word.lower() not in stopwords.words('english')]
    
    #3
    return clean_words
    

In [31]:
df['message'].head().apply(process_text)

0    [content, length, 3386, appleiss, research, ce...
1    [lang, classification, grimes, joseph, e, barb...
2    [posting, inquiry, sergei, atamas, satamas, um...
3    [colleague, researching, differing, degrees, r...
4    [earlier, morning, phone, friend, mine, living...
Name: message, dtype: object

In [32]:
#CONVERTING THE COLLECTION OF TEXT TO A MATRIX OF TOKENS
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(analyzer = process_text).fit_transform(df['message'])

In [33]:
#Split the dataset into (80%)training and (20%)testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(bow,df['label'],test_size=0.20, random_state = 0)

In [34]:
#get the shape of (bag of words)bow
bow.shape

(2876, 64661)

In [35]:
#create and train the Naive bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [36]:
#Print the Prediction
print(classifier.predict(X_train))

[0 0 0 ... 0 0 0]


In [37]:
#Print the Actual Vaues
print(y_train.values)

[0 0 0 ... 0 0 0]


In [39]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion matrix:  \n',confusion_matrix(y_train,pred))
print()
print('Accuracy:  ',accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1914
           1       0.99      0.99      0.99       386

    accuracy                           1.00      2300
   macro avg       0.99      1.00      1.00      2300
weighted avg       1.00      1.00      1.00      2300


Confusion matrix:  
 [[1910    4]
 [   2  384]]

Accuracy:   0.9973913043478261


In [40]:
#check on test dataset

In [41]:
#Print the Prediction
print(classifier.predict(X_test))

[0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0
 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 1 0 0 0 0 

In [42]:
#Print the Actual Vaues
print(y_test.values)

[0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0
 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 1 0 0 0 0 

In [43]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion matrix:  \n',confusion_matrix(y_test,pred))
print()
print('Accuracy:  ',accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       494
           1       0.93      1.00      0.96        82

    accuracy                           0.99       576
   macro avg       0.97      0.99      0.98       576
weighted avg       0.99      0.99      0.99       576


Confusion matrix:  
 [[488   6]
 [  0  82]]

Accuracy:   0.9895833333333334
